In [6]:
import torch
import numpy as np

In [7]:
print(torch.zeros(3, 3))
print(torch.rand(5, 2))
torch.ones(2, 4)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.1326, 0.1896],
        [0.3735, 0.5133],
        [0.1249, 0.0039],
        [0.7488, 0.3787],
        [0.6922, 0.0405]])


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
# mixing types
float_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)
int_tensor = torch.tensor([1, 2, 3], dtype=torch.int64)

mix_tensor = int_tensor + float_tensor

print(f"mixed type: {mix_tensor.dtype}")

mixed type: torch.float32


In [26]:
# creating tensors
my_distances = [[3.0], [7.0], [12.0], [18.0]]
tensor_from_list = torch.tensor(my_distances)

# numpy array
np_array = np.array([1.0, 2.0, 3.0])
tensor_from_numpy = torch.from_numpy(np_array)
# Shares memory changing np_array would also change tensor_from_numpy vice versa
np_array[0] = 4.0
print(tensor_from_numpy)


print(tensor_from_list.shape)
print(tensor_from_numpy.shape)

tensor([4., 2., 3.], dtype=torch.float64)
torch.Size([4, 1])
torch.Size([3])


In [ ]:
# reshaping tensors
single_distance = torch.tensor(25.0)

# add batch dim
with_batch = single_distance.unsqueeze(0)
print(with_batch.shape) # torch.Size([1])

ready_for_model = with_batch.unsqueeze(1)
print(ready_for_model.shape) # torch.Size([1, 1])

squeezed = ready_for_model.squeeze()
print(squeezed) # tensor(25.)
print(squeezed.shape) # torch.Size([])

torch.Size([1])
torch.Size([1, 1])
tensor(25.)
torch.Size([])


In [ ]:
# indexing and slicing
data = torch.tensor([[14.9], [24.1], [34.6], [45.2]])

print(data[0]) # tensor([14.9000])
print(data[1:3]) # tensor([[24.1000], [34.6000]])
print(data[:2]) # tensor([[14.9000], [24.1000]])

# works exactly on 1 item
print(data[0].item()) # 14.899999618530273

# below code will give error - a Tensor with 2 elements cannot be converted to Scalar
# print(data[1:3].item()) # error

# multiple features per sample
data = torch.tensor([[13.0, 8.0, 1.0], # distance, hour, weather
                      [7.0, 17.0, 2.0],
                      [12.0, 12.0, 1.0]])

print(data[:, 0]) # distances: tensor([13.,  7., 12.])
print(data[:, 1]) # hour: tensor([ 8., 17., 12.])
print(data[:, 2]) # weather tensor([1., 2., 1.])

tensor([14.9000])
tensor([[24.1000],
        [34.6000]])
tensor([[14.9000],
        [24.1000]])
14.899999618530273
tensor([13.,  7., 12.])
tensor([ 8., 17., 12.])
tensor([1., 2., 1.])


In [49]:
# Tensor Math (Broadcasting)
distances = torch.tensor([[3.0], [7.0], [12.0]])
weight = 2.3
bias = 8.0

result = weight * distances + bias

print(result)
print(result.shape)

tensor_one = torch.tensor([[1.0], [2.0], [3.0]])
tensor_two = torch.tensor([[1.0]])
tensor_result = tensor_one + tensor_two
print(tensor_result)
print(tensor_result.shape)

tensor_a = torch.tensor([[1.0], [2.0], [3.0]])
tensor_b = torch.tensor([1.0, 2.0, 3.0])
print(tensor_a.shape) # shape (3, 1)
print(tensor_b.shape) # shape (1, 3)

tensor_ab = tensor_a + tensor_b
print(tensor_ab)
print(tensor_ab.shape)



tensor([[14.9000],
        [24.1000],
        [35.6000]])
torch.Size([3, 1])
tensor([[2.],
        [3.],
        [4.]])
torch.Size([3, 1])
torch.Size([3, 1])
torch.Size([3])
tensor([[2., 3., 4.],
        [3., 4., 5.],
        [4., 5., 6.]])
torch.Size([3, 3])
